// Diagnostic-only integration tests that compare the Swift port's output
// against PNG goldens generated by the original ObjC CocoaLUT pipeline
// (see scripts/generate-lut-goldens). The source .cube files live outside
// this repository; supply their directory via the LUT_GOLDEN_FILTERS_DIR
// environment variable. When the variable is unset or the directory is
// missing the suite no-ops, so this file is safe to ship in CI.
//
// Goal: catch any pixel drift between ports while we audit colour parity.
// Once we're confident the port matches, this suite can be commented out
// or removed.

#if canImport(AppKit) && canImport(CoreImage)
import AppKit
import CoreGraphics
import CoreImage
import Foundation
import Testing
@testable import CocoaLUTSwift

@Suite(.serialized)
struct LUTGoldenIntegrationTests {
    // Filter directory is provided per-developer via env var so we don't
    // bake any private path into the codebase. Unset → empty arguments →
    // suite is a no-op.
    static var filtersDir: String? {
        ProcessInfo.processInfo.environment["LUT_GOLDEN_FILTERS_DIR"]
    }

    static var allFilterNames: [String] {
        guard let dir = filtersDir,
              FileManager.default.fileExists(atPath: dir) else { return [] }
        let names = (try? FileManager.default.contentsOfDirectory(atPath: dir)) ?? []
        return names.compactMap { name -> String? in
            guard name.hasSuffix(".cube") else { return nil }
            return String(name.dropLast(".cube".count))
        }.sorted()
    }

    /// Goldens directory. Resolved off the test file's own path so tests
    /// keep working when the directory is git-ignored — `#filePath` survives
    /// even though Goldens isn't bundled as a target resource.
    static func goldensDir(file: StaticString = #filePath) -> URL {
        URL(fileURLWithPath: "\(file)").deletingLastPathComponent()
            .appendingPathComponent("Goldens")
    }

    @MainActor
    @Test(arguments: LUTGoldenIntegrationTests.allFilterNames)
    func goldenMatches(filterName: String) throws {
        guard let dir = Self.filtersDir,
              FileManager.default.fileExists(atPath: dir) else {
            // No source filters configured — not a failure, the suite only
            // asserts when the developer points it at a local checkout.
            return
        }

        let cubeURL = URL(fileURLWithPath: dir)
            .appendingPathComponent("\(filterName).cube")
        let cubeData = try Data(contentsOf: cubeURL)
        // LUTFormatterCube here resolves to the ObjC-compat shim that returns
        // a LUT directly. Use the inner LUTCubeFormatter API for the typed
        // payload — we want the LUT3D variant for filter generation.
        let parsed = try LUTCubeFormatter.read(string: try #require(String(data: cubeData, encoding: .utf8)))
        guard case .lut3D(let lut3D) = parsed else {
            Issue.record("\(filterName): expected lut3D payload")
            return
        }

        let goldensDir = Self.goldensDir()
        let inputURL = goldensDir.appendingPathComponent("_input.png")
        let goldenURL = goldensDir.appendingPathComponent("\(filterName).png")
        guard FileManager.default.fileExists(atPath: inputURL.path),
              FileManager.default.fileExists(atPath: goldenURL.path) else {
            // Goldens haven't been generated locally yet — silent no-op so
            // the suite doesn't fail in fresh clones.
            return
        }

        let actualBytes = try renderFiltered(input: inputURL, lut: lut3D.asLUT())
        let goldenBytes = try loadDeviceRGBA8(url: goldenURL)

        #expect(actualBytes.count == goldenBytes.count, "\(filterName): pixel buffer size mismatch")
        if actualBytes.count == goldenBytes.count {
            // 100% identical match — first failure dominates the diff so
            // we report the worst per-channel error to make debugging
            // easier when this regresses.
            var maxAbs: Int = 0
            var totalAbs: Int = 0
            actualBytes.withUnsafeBufferPointer { a in
                goldenBytes.withUnsafeBufferPointer { g in
                    for i in 0..<a.count {
                        let delta = abs(Int(a[i]) - Int(g[i]))
                        if delta > maxAbs { maxAbs = delta }
                        totalAbs += delta
                    }
                }
            }
            let avg = Double(totalAbs) / Double(actualBytes.count)
            #expect(maxAbs == 0, "\(filterName): max channel delta = \(maxAbs) (avg \(avg))")
        }
    }

    // MARK: - Helpers

    @MainActor
    private func renderFiltered(input inputURL: URL, lut: LUT) throws -> [UInt8] {
        let nsImage = try #require(NSImage(contentsOf: inputURL), "could not load input PNG")
        guard let processed = lut.process(nsImage: nsImage, renderPath: .coreImage) else {
            Issue.record("process(nsImage:) returned nil")
            return []
        }
        return try bytes(of: processed)
    }

    private func loadDeviceRGBA8(url: URL) throws -> [UInt8] {
        let image = try #require(NSImage(contentsOf: url))
        return try bytes(of: image)
    }

    /// Renders an NSImage into a deviceRGB / RGBA8 buffer with origin at
    /// (0,0). All goldens and Swift outputs flow through this same path so
    /// PNG decoding quirks (gAMA chunks, color-profile reinterpretation)
    /// don't alter the comparison.
    private func bytes(of image: NSImage) throws -> [UInt8] {
        let width = Int(round(image.size.width))
        let height = Int(round(image.size.height))
        let bytesPerRow = width * 4
        var data = [UInt8](repeating: 0, count: bytesPerRow * height)
        let colorSpace = CGColorSpaceCreateDeviceRGB()
        let info = CGImageAlphaInfo.premultipliedLast.rawValue | CGBitmapInfo.byteOrder32Big.rawValue
        try data.withUnsafeMutableBufferPointer { buffer in
            guard let ctx = CGContext(data: buffer.baseAddress,
                                       width: width,
                                       height: height,
                                       bitsPerComponent: 8,
                                       bytesPerRow: bytesPerRow,
                                       space: colorSpace,
                                       bitmapInfo: info) else {
                throw NSError(domain: "Goldens", code: 1, userInfo: nil)
            }
            var rect = NSRect(origin: .zero, size: NSSize(width: width, height: height))
            guard let cgImage = image.cgImage(forProposedRect: &rect, context: nil, hints: nil) else {
                throw NSError(domain: "Goldens", code: 2, userInfo: nil)
            }
            ctx.draw(cgImage, in: rect)
        }
        return data
    }
}
#endif
